version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: warikan_api
    container_name: warikan_api
    ports:
      - 8080:8080
    volumes:
      - $PWD/build/libs/my-application.jar:/app/my-application.jar
    depends_on:
      - postgresql
    environment:
      #- COGNITO_DOMAIN= # need
      #- COGNITO_CLIENT_ID= # need
      #- COGNITO_CLIENT_SECRET= # need
      - GOOGLE_CLIENT_ID = 1022619172000-rbrqs8fhj094mq8eskht640dcs0euokb.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET = 4tH9Le7Xer7j4w_x67IdhLW9

  postgresql:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    image: warikan_postgresql
    container_name: warikan_postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: warikan
      POSTGRES_DB: warikan
      POSTGRES_PASSWORD: warikan