version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: warikan_api
    container_name: warikan_api
    ports:
      - 8080:8080
    volumes:
      - $PWD/build/libs/my-application.jar:/app/my-application.jar
    depends_on:
      - postgresql
    environment:
      AWS_REGION: "ap-northeast-1"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""

  postgresql:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    image: warikan_postgresql
    container_name: warikan_postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: warikan
      POSTGRES_DB: warikan
      POSTGRES_PASSWORD: warikan